// Auto-generated by LibreLane
module grouper_soc_chip_core(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input input_in,
  output input_pu,
  output input_pd,
  input[39:0] bidir_in,
  output[39:0] bidir_out,
  output[39:0] bidir_oe,
  output[39:0] bidir_cs,
  output[39:0] bidir_sl,
  output[39:0] bidir_ie,
  output[39:0] bidir_pu,
  output[39:0] bidir_pd
);
endmodule
