[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "grouper-dv"
version = "0.0.1"

dependencies = [
  "fusesoc==2.4.6",
  "cocotb==2.0.1",
  "pyuvm==4.0.1",
  "edalize==0.6.8",
  "pyyaml==6.0.3",
  "pyserial==3.5"
]

[tool.setuptools.packages.find]
include = ["hw*"]
