// ROM

// Contents come from code.vmem / code.hex, both generated by
// sw/scripts/build_bootloader.sh 

module rom_ss #(
  parameter int  ADDR_WIDTH = 8
) (
  input  logic                  clk,
  input  logic [ADDR_WIDTH-1:0] rom_addr,
  input  logic                  rom_read,
  output logic [31:0]           rom_rdata
);

  localparam int MEM_WORDS = 'hb6;
  localparam int ACTUAL_MEM_ADDR_WIDTH = $clog2(MEM_WORDS);

  // Memory Array  
  logic [31:0] memory [0:MEM_WORDS-1];

  // Load ROM contents
`ifdef ROM_INIT_CONST
  // Continuous assigns, one per word - for ASIC synthesis. $readmemh has no
  // synthesisable equivalent (standard cells have no initial-value mechanism),
  // so this is what actually produces a mask ROM. Resolved against
  // VERILOG_INCLUDE_DIRS; point that at sw/boot.
  `include "code.vmem"
`else
  initial
    // readmemh for simulation-time ROM initialisation, resolved against the
    // simulator's working directory.
    $readmemh("code.hex", memory);
`endif

  always_ff @(posedge clk) begin
    if (rom_read) begin
      rom_rdata <= memory[rom_addr[ACTUAL_MEM_ADDR_WIDTH-1:0]];
    end
  end

endmodule
