// ROM

`ifndef PROG_FILE_VMEM
`define PROG_FILE_VMEM "code.vmem"
`endif

`ifndef PROG_FILE_HEX
`define PROG_FILE_HEX "code.hex"
`endif

module rom_ss #(
  parameter int  ADDR_WIDTH = 8
) (
  input  logic                  clk,
  input  logic [ADDR_WIDTH-1:0] rom_addr,
  input  logic                  rom_read,
  output logic [31:0]           rom_rdata
);

  localparam int MEM_WORDS = 'hb6;
  localparam int ACTUAL_MEM_ADDR_WIDTH = $clog2(MEM_WORDS);

  // Memory Array  
  logic [31:0] memory [0:MEM_WORDS-1];

  // Load ROM contents
`ifdef ROM_INIT_CONST
  // include program instructions from file - for ASIC synthesis
  `include `PROG_FILE_VMEM
`else
  initial
    // readmemh for simulation-time ROM initialisation. The file is generated by sw/scripts/build_fw.sh
    $readmemh(`PROG_FILE_HEX, memory);
`endif

  always_ff @(posedge clk) begin
    if (rom_read) begin
      rom_rdata <= memory[rom_addr[ACTUAL_MEM_ADDR_WIDTH-1:0]];
    end
  end

endmodule
