###############################################################################
# Created by write_sdc
###############################################################################
current_design chip_core
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 62.5000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[0]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[10]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[11]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[12]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[13]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[14]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[15]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[16]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[17]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[18]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[19]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[1]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[20]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[21]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[22]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[23]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[24]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[25]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[26]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[27]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[28]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[29]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[2]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[30]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[31]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[32]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[32]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[33]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[33]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[34]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[34]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[35]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[35]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[36]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[36]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[37]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[37]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[38]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[38]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[39]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[39]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[3]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[4]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[5]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[6]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[7]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[8]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {bidir_in[9]}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {bidir_in[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {rst_n}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {rst_n}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[9]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[9]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[9]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[9]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[9]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[9]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[0]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[10]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[11]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[12]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[13]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[14]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[15]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[16]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[17]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[18]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[19]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[1]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[20]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[21]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[22]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[23]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[24]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[25]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[26]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[27]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[28]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[29]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[2]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[30]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[31]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[32]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[33]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[34]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[35]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[36]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[37]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[38]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[39]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[3]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[4]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[5]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[6]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[7]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[8]}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0729 [get_ports {input_pd}]
set_load -pin_load 0.0729 [get_ports {input_pu}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 3.0000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 16.0000 [current_design]
