###############################################################################
# Created by write_sdc
###############################################################################
current_design grouper_soc_chip_core
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 62.5000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_0_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_0_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_10_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_10_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_11_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_11_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_12_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_12_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_13_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_13_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_14_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_14_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_15_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_15_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_1_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_1_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_2_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_2_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_3_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_3_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_4_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_4_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_5_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_5_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_6_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_6_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_7_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_7_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_8_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_8_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_9_bidir_in}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_9_bidir_in}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {rst_n}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {rst_n}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {uart_rx}]
set_input_delay 12.5000 -clock [get_clocks {clk}] -max -add_delay [get_ports {uart_rx}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_0_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_10_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_11_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_12_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_13_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_14_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_15_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_1_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_2_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_3_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_4_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_5_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_6_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_7_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_8_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_cs}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_ie}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_oe}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_out}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_pd}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_pu}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {gpio_9_bidir_sl}]
set_output_delay 12.5000 -clock [get_clocks {clk}] -add_delay [get_ports {uart_tx}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_0_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_10_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_11_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_12_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_13_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_14_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_15_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_1_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_2_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_3_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_4_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_5_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_6_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_7_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_8_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_cs}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_ie}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_oe}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_out}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_pd}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_pu}]
set_load -pin_load 0.0729 [get_ports {gpio_9_bidir_sl}]
set_load -pin_load 0.0729 [get_ports {uart_tx}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 3.0000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 32.0000 [current_design]
